# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Saif's Portfolio"
name: "Saifeldeen Bassowa"
description: "Graduate Software engineer"
url: "https://yessamno.github.io"

author:
  name: "Saifeldeen Bassowa"
  avatar: "assets/images/profilepic.jpg"
  bio: "I have a clear, logical mind with a practical approach to problem-solving and a drive to see things through to completion. I have more than 4 years of experience in managing and leading teams across multiple sectors. I am eager to learn, I enjoy overcoming challenges, and I have a genuine interest in Software engineering and delivering high quality work and developing my own projects."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yessamno"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/saifledeenbassowa"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
